-- ============================================================
-- BANK FRAUD DETECTION SYSTEM (BFDS) - FalconEye
-- Script: Authentication Table — Sample User Data Insertion
-- Database : bank_fraud_detection_db
-- Version  : 1.0  |  Date: April 2026
-- ============================================================
-- ROLES COVERED:
--   1. super_admin        — Full system access
--   2. compliance_officer — Reports, alerts, audit logs
--   3. bank_employee      — User data, cards, transactions
--
-- ⚠ IMPORTANT NOTES FOR FRONTEND INTEGRATION:
--   • password_hash values below are PLACEHOLDERS only.
--   • Before connecting your frontend, replace each
--     password_hash with a real bcrypt hash generated by
--     your backend (Node.js / Python / .NET etc.)
--   • Never store or transmit plain-text passwords.
--   • The plain-text passwords shown in comments are for
--     your LOCAL DEV testing ONLY — remove them before
--     pushing to any shared or production environment.
-- ============================================================

USE bank_fraud_detection_db;
GO

-- ============================================================
-- CLEAN SLATE: Remove existing test users before re-inserting
-- ============================================================
DELETE FROM authentication
WHERE employee_id IN (
    'EMP-SA-001', 'EMP-SA-002',
    'EMP-CO-001', 'EMP-CO-002',
    'EMP-BE-001', 'EMP-BE-002', 'EMP-BE-003', 'EMP-BE-004',
    'EMP-BE-005', 'EMP-BE-006'
);
GO

-- ============================================================
-- SECTION 1: SUPER ADMIN (2 users)
-- Access: Everything — all tables, all users, all settings
-- ============================================================
INSERT INTO authentication
(
    employee_id,
    username,
    password_hash,
    salt,
    role,
    is_active,
    email,
    phone,
    mfa_enabled,
    mfa_secret_hash,
    must_change_password,
    password_changed_at
)
VALUES
(
    'EMP-SA-001',
    'admin.primary',
    -- Plain text (DEV ONLY): Admin@BFDS2026!
    '$2b$12$KIX8.pWqLm3nRvTzYoUeAOeM5HvJ2WqXpLm3nRvTzYoUeAOeM5H',
    'SALT$KIX8pWqLm3nRvTz',
    'super_admin',
    1,                              -- is_active: YES
    'admin.primary@bfds.bank',
    '3185550001',
    1,                              -- mfa_enabled: YES (mandatory for admins)
    'TOTP$SECRET$SA001$BASE32HASH',
    0,                              -- must_change_password: NO
    DATEADD(DAY, -30, GETUTCDATE())
),
(
    'EMP-SA-002',
    'admin.secondary',
    -- Plain text (DEV ONLY): Admin2@BFDS2026!
    '$2b$12$PQR9.xWqLm4nSvUzZpVfBPfN6IwK3XrYqMn4oSwUaZpVfBPfN6I',
    'SALT$PQR9xWqLm4nSvUz',
    'super_admin',
    1,
    'admin.secondary@bfds.bank',
    '3185550002',
    1,
    'TOTP$SECRET$SA002$BASE32HASH',
    0,
    DATEADD(DAY, -15, GETUTCDATE())
);
GO

-- ============================================================
-- SECTION 2: COMPLIANCE OFFICER (2 users)
-- Access: Read-only reports, transaction logs, alert tables,
--         audit logs — NO write access to core tables
-- ============================================================
INSERT INTO authentication
(
    employee_id,
    username,
    password_hash,
    salt,
    role,
    is_active,
    email,
    phone,
    mfa_enabled,
    mfa_secret_hash,
    must_change_password,
    password_changed_at
)
VALUES
(
    'EMP-CO-001',
    'compliance.officer1',
    -- Plain text (DEV ONLY): Comply@BFDS2026!
    '$2b$12$ABC1.mNpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGh',
    'SALT$ABC1mNpQrStUvWx',
    'compliance_officer',
    1,
    'compliance.officer1@bfds.bank',
    '3185550003',
    1,
    'TOTP$SECRET$CO001$BASE32HASH',
    0,
    DATEADD(DAY, -45, GETUTCDATE())
),
(
    'EMP-CO-002',
    'compliance.officer2',
    -- Plain text (DEV ONLY): Comply2@BFDS2026!
    '$2b$12$DEF2.nOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfG',
    'SALT$DEF2nOpQrStUvWx',
    'compliance_officer',
    1,
    'compliance.officer2@bfds.bank',
    '3185550004',
    0,                              -- mfa_enabled: optional for compliance
    NULL,
    1,                              -- must_change_password: YES (first login)
    NULL
);
GO

-- ============================================================
-- SECTION 3: BANK EMPLOYEE (6 users)
-- Access: View user profiles, cards, transactions, alerts,
--         devices — standard operational access
-- ============================================================
INSERT INTO authentication
(
    employee_id,
    username,
    password_hash,
    salt,
    role,
    is_active,
    email,
    phone,
    mfa_enabled,
    mfa_secret_hash,
    must_change_password,
    password_changed_at
)
VALUES

-- ── Active employee — standard access ──────────────────────
(
    'EMP-BE-001',
    'emp.john.doe',
    -- Plain text (DEV ONLY): Emp001@BFDS2026!
    '$2b$12$GHI3.oRsUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjK',
    'SALT$GHI3oRsUvWxYzAb',
    'bank_employee',
    1,
    'john.doe@bfds.bank',
    '3185550005',
    0,
    NULL,
    0,
    DATEADD(DAY, -60, GETUTCDATE())
),

-- ── Active employee — standard access ──────────────────────
(
    'EMP-BE-002',
    'emp.alice.smith',
    -- Plain text (DEV ONLY): Emp002@BFDS2026!
    '$2b$12$JKL4.pStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl',
    'SALT$JKL4pStUvWxYzAb',
    'bank_employee',
    1,
    'alice.smith@bfds.bank',
    '3185550006',
    0,
    NULL,
    0,
    DATEADD(DAY, -20, GETUTCDATE())
),

-- ── Active employee — must change password on first login ───
(
    'EMP-BE-003',
    'emp.david.nguyen',
    -- Plain text (DEV ONLY): TempPass@2026!
    '$2b$12$MNO5.qTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLm',
    'SALT$MNO5qTuVwXyZaBc',
    'bank_employee',
    1,
    'david.nguyen@bfds.bank',
    '3185550007',
    0,
    NULL,
    1,                              -- must_change_password: YES
    NULL                            -- never changed yet
),

-- ── Active employee — MFA enabled ──────────────────────────
(
    'EMP-BE-004',
    'emp.sarah.connor',
    -- Plain text (DEV ONLY): Emp004@BFDS2026!
    '$2b$12$PQR6.rUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMn',
    'SALT$PQR6rUvWxYzAbCd',
    'bank_employee',
    1,
    'sarah.connor@bfds.bank',
    '3185550008',
    1,                              -- mfa_enabled: YES
    'TOTP$SECRET$BE004$BASE32HASH',
    0,
    DATEADD(DAY, -10, GETUTCDATE())
),

-- ── SUSPENDED / locked employee (too many failed attempts) ──
(
    'EMP-BE-005',
    'emp.michael.brown',
    -- Plain text (DEV ONLY): Emp005@BFDS2026!
    '$2b$12$STU7.sVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNo',
    'SALT$STU7sVwXyZaBcDe',
    'bank_employee',
    1,                              -- is_active: still active
    'michael.brown@bfds.bank',
    '3185550009',
    0,
    NULL,
    0,
    DATEADD(DAY, -90, GETUTCDATE())
),

-- ── DEACTIVATED employee (terminated / offboarded) ──────────
(
    'EMP-BE-006',
    'emp.olga.petrov',
    -- Plain text (DEV ONLY): Emp006@BFDS2026!
    '$2b$12$VWX8.tWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOp',
    'SALT$VWX8tWxYzAbCdEf',
    'bank_employee',
    0,                              -- is_active: NO (deactivated)
    'olga.petrov@bfds.bank',
    '3185550010',
    0,
    NULL,
    0,
    DATEADD(DAY, -180, GETUTCDATE())
);
GO

-- ============================================================
-- POST-INSERT: Update supplementary columns
-- (columns not in INSERT above — set realistic states)
-- ============================================================

-- EMP-BE-005: Simulate a locked account (5 failed attempts)
UPDATE authentication
SET
    failed_attempts = 5,
    locked_until    = DATEADD(MINUTE, 30, GETUTCDATE()),
    updated_at      = GETUTCDATE()
WHERE employee_id = 'EMP-BE-005';

-- EMP-BE-006: Set deactivated_at timestamp for the offboarded employee
UPDATE authentication
SET
    deactivated_at  = DATEADD(DAY, -30, GETUTCDATE()),
    updated_at      = GETUTCDATE()
WHERE employee_id = 'EMP-BE-006';

-- All users: set a realistic last_login_at (except new/deactivated)
UPDATE authentication
SET
    last_login_at = DATEADD(HOUR, -CHECKSUM(NEWID()) % 72, GETUTCDATE()),
    last_login_ip = CASE role
                        WHEN 'super_admin'        THEN '10.0.0.1'
                        WHEN 'compliance_officer' THEN '10.0.0.2'
                        ELSE '192.168.1.' + CAST(ABS(CHECKSUM(NEWID())) % 50 + 10 AS NVARCHAR(5))
                    END,
    updated_at    = GETUTCDATE()
WHERE employee_id NOT IN ('EMP-BE-003', 'EMP-BE-006');  -- new hire + deactivated have no login
GO

-- ============================================================
-- VERIFY: View all inserted authentication records
-- ============================================================
SELECT
    auth_id,
    employee_id,
    username,
    role,
    email,
    phone,
    is_active,
    mfa_enabled,
    must_change_password,
    failed_attempts,
    locked_until,
    last_login_at,
    last_login_ip,
    password_changed_at,
    deactivated_at,
    created_at,
    CASE
        WHEN is_active    = 0                 THEN '🔴 Deactivated'
        WHEN locked_until > GETUTCDATE()      THEN '🔒 Locked'
        WHEN must_change_password = 1         THEN '🔑 Must Change Password'
        WHEN failed_attempts BETWEEN 3 AND 4  THEN '⚠ At Risk'
        ELSE                                       '✅ Active'
    END AS account_health
FROM   authentication
ORDER  BY
    CASE role
        WHEN 'super_admin'        THEN 1
        WHEN 'compliance_officer' THEN 2
        WHEN 'bank_employee'      THEN 3
    END,
    auth_id;
GO

-- ============================================================
-- QUICK REFERENCE — Frontend Login Credentials (DEV ONLY)
-- Remove / replace all password_hash values before production
-- ============================================================
/*
╔══════════════════╦══════════════════════╦═══════════════════════╦══════════════════════╗
║ Role             ║ Username             ║ Password (DEV ONLY)   ║ Account State        ║
╠══════════════════╬══════════════════════╬═══════════════════════╬══════════════════════╣
║ super_admin      ║ admin.primary        ║ Admin@BFDS2026!       ║ ✅ Active + MFA      ║
║ super_admin      ║ admin.secondary      ║ Admin2@BFDS2026!      ║ ✅ Active + MFA      ║
╠══════════════════╬══════════════════════╬═══════════════════════╬══════════════════════╣
║ compliance_ofcr  ║ compliance.officer1  ║ Comply@BFDS2026!      ║ ✅ Active + MFA      ║
║ compliance_ofcr  ║ compliance.officer2  ║ Comply2@BFDS2026!     ║ 🔑 Must Change Pass  ║
╠══════════════════╬══════════════════════╬═══════════════════════╬══════════════════════╣
║ bank_employee    ║ emp.john.doe         ║ Emp001@BFDS2026!      ║ ✅ Active            ║
║ bank_employee    ║ emp.alice.smith      ║ Emp002@BFDS2026!      ║ ✅ Active            ║
║ bank_employee    ║ emp.david.nguyen     ║ TempPass@2026!        ║ 🔑 Must Change Pass  ║
║ bank_employee    ║ emp.sarah.connor     ║ Emp004@BFDS2026!      ║ ✅ Active + MFA      ║
║ bank_employee    ║ emp.michael.brown    ║ Emp005@BFDS2026!      ║ 🔒 Locked (5 fails)  ║
║ bank_employee    ║ emp.olga.petrov      ║ Emp006@BFDS2026!      ║ 🔴 Deactivated       ║
╚══════════════════╩══════════════════════╩═══════════════════════╩══════════════════════╝

⚠ BACKEND INTEGRATION NOTES:
   1. Hash passwords with bcrypt (cost factor 12+) before storing.
   2. Generate a cryptographically random salt per user (16+ bytes).
   3. For MFA users, generate a real TOTP secret (Base32, 20 bytes)
      and store only the hashed version in mfa_secret_hash.
   4. Your login endpoint should:
        a. SELECT by username
        b. Verify bcrypt(input_password, stored_hash)
        c. Check is_active = 1
        d. Check locked_until IS NULL OR locked_until < GETUTCDATE()
        e. Check must_change_password — redirect to reset page if 1
        f. If MFA enabled — prompt for TOTP code before granting session
        g. On success — INSERT into authentication_audit_log (login_success)
        h. On failure — INSERT into authentication_audit_log (login_failure)
                        + increment failed_attempts
                        + lock account if failed_attempts >= 5
*/

-- ============================================================
-- END OF SCRIPT: Authentication Sample Data
-- ============================================================
